-- Phase 13: Security & Governance
-- Apply using ACCOUNTADMIN, then perform negative-access validation.

USE ROLE ACCOUNTADMIN;

-- Ingestion service
GRANT USAGE ON WAREHOUSE GFS_INGEST_WH TO ROLE GFS_INGESTION_SVC;
GRANT USAGE ON DATABASE GFS_DEV TO ROLE GFS_INGESTION_SVC;
GRANT USAGE ON SCHEMA GFS_DEV.RAW TO ROLE GFS_INGESTION_SVC;
GRANT USAGE ON SCHEMA GFS_DEV.CONTROL TO ROLE GFS_INGESTION_SVC;
GRANT SELECT ON GFS_DEV.RAW.FAOSTAT_QCL TO ROLE GFS_INGESTION_SVC;
GRANT USAGE ON PROCEDURE GFS_DEV.CONTROL.SP_MERGE_QCL_CLEAN(VARCHAR)
TO ROLE GFS_INGESTION_SVC;

-- Analyst
GRANT USAGE ON WAREHOUSE GFS_ANALYTICS_WH TO ROLE GFS_ANALYST;
GRANT USAGE ON DATABASE GFS_DEV TO ROLE GFS_ANALYST;
GRANT USAGE ON SCHEMA GFS_DEV.CONSUMPTION TO ROLE GFS_ANALYST;
GRANT USAGE ON SCHEMA GFS_DEV.PUBLISH TO ROLE GFS_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA GFS_DEV.CONSUMPTION TO ROLE GFS_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA GFS_DEV.CONSUMPTION TO ROLE GFS_ANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA GFS_DEV.PUBLISH TO ROLE GFS_ANALYST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA GFS_DEV.PUBLISH TO ROLE GFS_ANALYST;

-- Project role hierarchy
GRANT ROLE GFS_ANALYST TO ROLE GFS_DEVELOPER;
GRANT ROLE GFS_DEVELOPER TO ROLE GFS_PLATFORM_ADMIN;
GRANT ROLE GFS_INGESTION_SVC TO ROLE GFS_PLATFORM_ADMIN;
GRANT ROLE GFS_TRANSFORM_SVC TO ROLE GFS_PLATFORM_ADMIN;
GRANT ROLE GFS_PLATFORM_ADMIN TO ROLE SYSADMIN;

-- Validation examples. Run manually and expect the UPDATE statements to fail.
-- USE ROLE GFS_INGESTION_SVC;
-- SELECT COUNT(*) FROM GFS_DEV.RAW.FAOSTAT_QCL;
-- UPDATE GFS_DEV.CLEAN.FAOSTAT_QCL SET value = value WHERE 1 = 0;
--
-- USE ROLE GFS_ANALYST;
-- SELECT COUNT(*) FROM GFS_DEV.CONSUMPTION.FACT_CROPS_LIVESTOCK;
-- UPDATE GFS_DEV.CONSUMPTION.FACT_CROPS_LIVESTOCK SET value = value WHERE 1 = 0;
