USE ROLE GFS_PLATFORM_ADMIN;

USE DATABASE GFS_DEV;
USE SCHEMA RAW;

CREATE ICEBERG TABLE IF NOT EXISTS FAOSTAT_QCL
    CATALOG = 'GFS_DELTA_CATALOG'
    EXTERNAL_VOLUME = 'GFS_DEV_DELTA_EXT_VOL'
    BASE_LOCATION = 'faostat/qcl/'
    AUTO_REFRESH = TRUE
    COMMENT = 'Read-only RAW Delta Direct table for FAOSTAT QCL data';