USE ROLE GFS_PLATFORM_ADMIN;

USE DATABASE GFS_DEV;
USE SCHEMA CONTROL;


CREATE TABLE IF NOT EXISTS RAW_LOAD_AUDIT (
    AUDIT_ID                STRING,
    SOURCE_SYSTEM           STRING,
    SOURCE_DOMAIN           STRING,
    SOURCE_ROW_COUNT        NUMBER,
    RAW_ROW_COUNT           NUMBER,
    COUNT_MATCH_FLAG        BOOLEAN,
    DELTA_TABLE             STRING,
    INGESTION_MODE          STRING,
    CHECKED_AT_UTC          TIMESTAMP_TZ,
    CHECKED_BY              STRING
);