SELECT CURRENT_USER();

USE ROLE SECURITYADMIN;

GRANT ROLE GFS_DEVELOPER TO USER <YOUR_USERNAME>;

USE ROLE GFS_DEVELOPER;
USE SECONDARY ROLES NONE;

USE WAREHOUSE GFS_TRANSFORM_WH;
USE DATABASE GFS_DEV;

CREATE TABLE GFS_DEV.CLEAN.RBAC_TEST (
    ID NUMBER,
    TEST_VALUE VARCHAR
);

INSERT INTO GFS_DEV.CLEAN.RBAC_TEST
VALUES (1, 'permission test');

SELECT *
FROM GFS_DEV.CLEAN.RBAC_TEST;

DROP TABLE GFS_DEV.CLEAN.RBAC_TEST;

CREATE TABLE GFS_DEV.RAW.RBAC_TEST (
    ID NUMBER
);